grafana:
  adminPassword: change-me

  service:
    type: ClusterIP

  ingress:
    enabled: false

  persistence:
    enabled: false

  additionalDataSources:
    - name: Loki
      type: loki
      access: proxy
      url: http://loki-gateway.observability.svc.cluster.local
      isDefault: false
      editable: true

  sidecar:
    dashboards:
      enabled: true
      searchNamespace: ALL

prometheus:
  prometheusSpec:
    retention: 10d
    scrapeInterval: 30s

alertmanager:
  enabled: true

kube-state-metrics:
  enabled: true

nodeExporter:
  enabled: true

defaultRules:
  create: true
